---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  type: NodePort
  selector:
    app: homeassistant
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123  
  externalIPs:
    - 192.168.0.211
    - 192.168.0.221
    - 192.168.0.222 
