apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homeassistant
  namespace: default
  labels:
    monitoring.styxut.net/scrape: "true"
spec:
  selector:
    matchLabels:
      app: homeassistant
  endpoints:
    - port: http
      path: /api/prometheus
      interval: 60s
      scrapeTimeout: 15s
