---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    app: homeassistant
    monitoring.styxut.net/scrape: "true"
spec:
  selector:
    app: homeassistant
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123  
