---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: synology-homeassistant
spec:
  capacity:
    storage: .003Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: synology
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: synology.home 
    path: "/volume1/k8s-pv01"
