---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology
  resources:
    requests:
      storage: .003Gi
