apiVersion: v1
kind: PersistentVolume
metadata: 
  name: synology
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: synology
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.0.2
    path: "/volume1/k8s-pv01"
